### PR TITLE
🌱 update to go 1.21

### PR DESCRIPTION
**Pull request by kranurag7**
this commit updates to go 1.21

**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squash commits
- [ ] include documentation
- [ ] add unit tests

### CODE REVIEW

**Review by janiskemper — APPROVED** [review]

**Comment by janiskemper** [comment]
@batistein do you have anything to add?

**Comment by batistein** [comment]
@kranurag7 what about linting? I saw that no linter was triggered.. Usually a golang update also requires adjusting go code..

**Comment by kranurag7** [comment]
The linting is embedded in `make verify` target. 
Ref: https://github.com/hivelocity/hivelocity-cloud-controller-manager/actions/runs/6676009895/job/18144641479?pr=26#step:4:16

**Comment by batistein** [comment]
please check the golangci lint: https://github.com/hivelocity/hivelocity-cloud-controller-manager/blob/main/.golangci.yaml#L99-L101

This needs to be updated as well

**Review by batistein — APPROVED** [review]

**Pull request merged**
